. steps/install_xcode.sh
. steps/install_homebrew.sh
. steps/install_wget.sh
. steps/install_telnet.sh
. steps/install_gettext.sh
. steps/install_iterm.sh
. steps/install_zsh.sh
. steps/pure_zsh.sh
. steps/material_theme.sh
. steps/vim.sh
. steps/install_git.sh
. steps/install_python.sh
. steps/install_virtualenv.sh
. steps/install_php.sh
. steps/install_go.sh
. steps/install_composer.sh
. steps/install_npm.sh
. steps/install_ansible.sh
. steps/install_diff_so_fancy.sh
. steps/install_virtualbox.sh
. steps/install_vagrant.sh
. steps/install_docker.sh
. steps/install_watch.sh
. steps/install_tree.sh
. steps/install_macpass.sh
. steps/install_google_chrome.sh
. steps/install_google_backup_and_sync.sh
. steps/install_sequel_pro.sh
. steps/install_postman.sh
. steps/install_apache_directory_studio.sh
. steps/install_bettertouchtool.sh
. steps/install_jetbrains_toolbox.sh
. steps/install_mongodb.sh
. steps/install_mongodb_compass.sh
. steps/install_filezilla.sh
. steps/install_java.sh
. steps/install_slack.sh
. steps/install_evernote.sh
. steps/install_colloquy.sh
. steps/install_rtv.sh
. steps/install_twine.sh
. steps/install_travis.sh
. steps/dotfiles.sh
